apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: myapp-stable-ingress
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: myapp-stable-service
            port:
              number: {{ .Values.service.port }}
